name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # or 'main' if that's your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Since your index.html is in the root
          cname: zivatonline.com # Optional: remove this line if not using custom domain
